#include <furi.h>

// /* generated by fbt from .png files in images folder */
// #include <two_can_app_icons.h>

int32_t two_can_app_app(void* p) {
    UNUSED(p);
    FURI_LOG_I("TEST", "Hello world");
    FURI_LOG_I("TEST", "I'm 2can_app!");

    return 0;
}
